= aws-modernization-workshop
Workshopper setup for aws-modernization-workshop

== Deploy to AWS
=== Pre-Requisites
. http://www.docker.com[Docker client]
. https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html[AWS CLI]

=== Download `Workshooper` Image
. Download the docker image from the *DockerHub* repository.
+
----
docker pull osevg/workshopper
----

=== Upload `Worksopper` image to AWS
. Create the https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-create.html[Amazon ECR] Repository with the name `woprkshooper`.
. Log into the newly created repository.

+
----
$(aws ecr get-login --no-include-email --region us-west-2)
----
. Tag the pulled image with the AWS repository *URI*.
+
----
docker tag osevg/workshopper {AWS ACCOUNT ID}.dkr.ecr.us-west-2.amazonaws.com/workshopper:latest
----
. Push the image to your newly created AWS repository.
+
----
docker push {AWS ACCOUNT ID}.dkr.ecr.us-west-2.amazonaws.com/workshopper:latest
----
. Test the pushed image locally
+
----
docker run -it --rm -p 8080:8080 \
    -e CONTENT_URL_PREFIX=https://raw.githubusercontent.com/darkreapyre/aws-modernization-workshop/master \
    -e WORKSHOPS_URLS=https://raw.githubusercontent.com/darkreapyre/aws-modernization-workshop/master/workshops/modernization-workshop.yml  \
    {AWS ACCOUNT ID}.dkr.ecr.us-west-2.amazonaws.com/workshopper:latest
----
+
NOTE: You should now be able to see the workshop on http://localhost:8080
. Deploy the pushed image into production.
  .. Log into the AWS CloudFormation Console.
  .. Click [Create Stack].
  .. Click [Upload template file].
  .. Click [Choose file].
  .. Select the `workshopper-cfn-template.yaml` file.
  .. Click [Next].
  .. Enter a [Stack name].
  .. Ensure all the _parameters_ are correct and add the following:
  ... `Image` - The **URI* for the `workshopper` image create in _Step 4_.
  ... `SubnetA`
  ... `SubnetB`
  ... `VPC`
  .. Click [Next] and complete the additional steps of the wizard.
. Test the production workshop.
  .. Once the teamplate has been deployed, click the [Output] tab for the newly created stack.

+
TIP: Create a shortened *URL* for easier reference to the workshop at http://bit.ly[bitly].

== Local Testing
To test any changes you have made locally make sure you have docker installed you are in this repository root.

[source,shell]
----
docker run -it --rm -p 8080:8080 -v `pwd`:/content \
    -e CONTENT_URL_PREFIX=file:///content \
    -e WORKSHOPS_URLS=file:///content/workshops/modernization-workshop.yml \
    osevg/workshopper
----